// Generated by CoffeeScript 1.7.1
(function() {
  var User;

  User = require('../app/models/user');

  module.exports = function(app) {
    var editChar;
    app.io.route('edit', function(req) {
      switch (req.data[0]) {
        case 'self':
          return editChar(req, 0);
        case 'char':
          console.log("req.session.passport.user: " + JSON.stringify(req.session.passport.user));
          return User.findById(req.session.passport.user, function(err, data) {
            if (err != null) {
              console.log("ERROR: " + err);
              return req.io.emit('error', err);
            } else {
              if (data.chars.length < 2) {
                return req.io.emit('message', "You don't have any characters to edit.");
              } else {
                return req.io.emit('message', "Sorry, I can't edit characters at this time.");
              }
            }
          });
        case 'room':
          return req.io.emit('message', "Sorry, I can't edit rooms at this time.");
        case void 0:
          return req.io.emit('prompt', {
            message: 'What would you like to edit?\n    self    char    room',
            command: 'edit',
            args: req.data
          });
        default:
          return req.io.emit('message', "I cannot edit \"" + req.data[0] + "\".");
      }
    });
    return editChar = function(req, index) {
      return req.io.emit('message', "Sorry, I cannot edit characters at this time.");
    };
  };

}).call(this);
