// Generated by CoffeeScript 1.7.1
(function() {
  var isLoggedIn;

  module.exports = function(app, passport) {
    app.get('/', function(req, res) {
      return res.render('index.ejs');
    });
    app.get('/verse', isLoggedIn, function(req, res) {
      return res.render('verse.ejs');
    });
    app.get('/logout', function(req, res) {
      req.logout();
      return res.redirect('/');
    });
    app.get('/tutorial', function(req, res) {
      return res.render('tutorial.ejs');
    });
    app.get('/login', function(req, res) {
      return res.render('login.ejs', {
        message: req.flash('loginMessage')
      });
    });
    app.post('/login', passport.authenticate('login', {
      successRedirect: '/verse',
      failureRedirect: '/login',
      failureFlash: true
    }));
    app.get('/signup', function(req, res) {
      return res.render('signup.ejs', {
        message: req.flash('signupMessage')
      });
    });
    app.post('/signup', passport.authenticate('signup', {
      successRedirect: '/verse',
      failureRedirect: '/signup',
      failureFlash: true
    }));
    app.get('/change', function(req, res) {
      return res.render('change.ejs', {
        message: req.flash('loginMessage')
      });
    });
    return app.post('/change', passport.authenticate('signup', {
      successRedirect: '/verse',
      failureRedirect: '/change',
      failureFlash: true
    }));
  };

  isLoggedIn = function(req, res, next) {
    if (req.isAuthenticated()) {
      return next();
    }
    return res.redirect('/');
  };

}).call(this);
