// Generated by CoffeeScript 1.7.1
(function() {
  var isLoggedIn;

  module.exports = function(app, passport) {
    app.get('/', function(req, res) {
      return res.render('index.ejs');
    });
    app.get('/profile', isLoggedIn, function(req, res) {
      return res.render('profile.ejs', {
        user: req.user
      });
    });
    app.get('/logout', function(req, res) {
      req.logout();
      return res.redirect('/');
    });
    app.get('/login', function(req, res) {
      return res.render('login.ejs', {
        message: req.flash('loginMessage')
      });
    });
    app.post('/login', passport.authenticate('local-login', {
      successRedirect: '/profile',
      failureRedirect: '/login',
      failureFlash: true
    }));
    app.get('/signup', function(req, res) {
      return res.render('signup.ejs', {
        message: req.flash('signupMessage')
      });
    });
    app.post('/signup', passport.authenticate('local-signup', {
      successRedirect: '/profile',
      failureRedirect: '/signup',
      failureFlash: true
    }));
    app.get('/connect/local', function(req, res) {
      return res.render('change.ejs', {
        message: req.flash('loginMessage')
      });
    });
    app.post('/connect/local', passport.authenticate('local-signup', {
      successRedirect: '/profile',
      failureRedirect: '/connect/local',
      failureFlash: true
    }));
    return app.get('/unlink/local', function(req, res) {
      var user;
      user = req.user;
      user.local.email = void 0;
      user.local.password = void 0;
      return user.save(function(err) {
        return res.redirect('/profile');
      });
    });
  };

  isLoggedIn = function(req, res, next) {
    if (req.isAuthenticated()) {
      return next();
    }
    return res.redirect('/');
  };

}).call(this);
