// Generated by CoffeeScript 1.7.1
(function() {
  var Char, User, bcrypt, mongoose;

  mongoose = require('mongoose');

  bcrypt = require('bcrypt-nodejs');

  Char = require('./char');

  User = mongoose.Schema({
    email: String,
    password: String,
    chars: [Char.schema]
  });

  User.methods.generateHash = function(password) {
    return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
  };

  User.methods.validPassword = function(password) {
    return bcrypt.compareSync(password, this.password);
  };

  module.exports = mongoose.model('User', User);

}).call(this);
