// Generated by CoffeeScript 1.7.1
(function() {
  var bcrypt, mongoose, userSchema;

  mongoose = require('mongoose');

  bcrypt = require('bcrypt-nodejs');

  userSchema = mongoose.Schema({
    email: String,
    password: String
  });

  userSchema.methods.generateHash = function(password) {
    return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
  };

  userSchema.methods.validPassword = function(password) {
    return bcrypt.compareSync(password, this.password);
  };

  module.exports = mongoose.model('User', userSchema);

}).call(this);
